#default values for single instantiation 
eureka:
  instance:
    status-page-url-path: /manage/info
    health-check-url-path: /manage/health
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.index:${server.port}}
  client:
    service-url:
      defaultZone: http://${APPLICATION_DOMAIN:${COMPUTERNAME:localhost}}:7261/eureka/

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: metrics,info,health
  endpoint:
    health:
      show-details: always

## Contract service configuration
contract-service:
  rootCredential: root:optimal
  serverIP: 192.168.31.24

## Scheduler
## sec(0-59) min(0-59) hour(0-23) day(1-31) month(1-12) day of the week(0:Sun,1:Mon,2:Tue,3:Wed,4:Thu,5:Fri,6:Sat,7:Sun)
schedulerCron: 0 0 8 * * *

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
