#default values for single instantiation 
spring:
  application:
    name: contractservice
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
  # Configurazione JMS Artemis Embedded
  artemis:
    mode: embedded
    embedded:
      enabled: true
      persistent: false
      data-directory: target/artemis-data
      queues: documentDeleted,contractProcessed
    broker-url: vm://localhost?broker.persistent=false
    user: admin
    password: admin
  # Disabilita JMS se non necessario
  jms:
    enabled: true

eureka:
  instance:
    status-page-url-path: /manage/info
    health-check-url-path: /manage/health
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.index:${server.port}}
  client:
    service-url:
      defaultZone: http://${APPLICATION_DOMAIN:${COMPUTERNAME:localhost}}:7261/eureka/

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: metrics,info,health,jms
  endpoint:
    health:
      show-details: always

## Contract service configuration
contract-service:
  rootCredential: root:optimal
  serverIP: 192.168.31.24

## DMS Service configuration
dms:
  service:
    url: http://192.168.31.24:7301
    trust-pattern: "192.168.31.*"
  security:
    trust:
      ip:
        pattern: 192.168.31.*

## Feign configuration
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
      dms:
        url: http://192.168.31.24:7301  # URL diretto invece di 'dms'
      bmp:
        connect-timeout: 30000
        read-timeout: 60000
        logger-level: full

## Scheduler
## sec(0-59) min(0-59) hour(0-23) day(1-31) month(1-12) day of the week(0:Sun,1:Mon,2:Tue,3:Wed,4:Thu,5:Fri,6:Sat,7:Sun)
## schedulerCron: 0 0 8 * * *
schedulerCron: 0 30 * * * *

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

# Logging per debug dettagliato
logging:
  level:
    org.springframework.jms: WARN
    org.apache.activemq: WARN
    com.os.services.contract: DEBUG
    com.os.services.contract.dao.ApiClient: TRACE
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG
    feign: DEBUG
    # Per vedere le richieste HTTP complete
    org.springframework.web.client.RestTemplate: DEBUG

# Configurazione degli endpoint
endpoints:
  dms:
    base-url: http://192.168.31.24:7301
  bpm:
    base-url: http://localhost:8080/bpm-service
    timeout:
      connect: 30000
      read: 60000

# O se usi application.properties:
# endpoints.bpm.base-url=http://localhost:8080/bpm
